### ISSUE TITLE
Add a radius to the georeference

### ISSUE THREAD

**Issue by karthik** [ropensci/ecoengine#49]
Requested by David Ackerly.

**Comment by mkoo** [comment]
Returning to this old issue: is the max uncertainty part of the $data when using ee_photos() command? I am trying to use the R package to find the min/max uncertainty of a collection in Calphotos and there's does not seem to be part of the dataframe. Is this an issue with the API or the package? Also following up with API folks

**Comment by karthik** [comment]
It's currently not.  It is probably an issue with the API or the functionality was added after this was developed. I'll investigate and see if this is being returned by the API and add it to `.$data` if available.

**Comment by mkoo** [comment]
HI Karthik, since I commented, I learned that it is not indexed in
ecoengine. Further it seems to have all the same value (1000 m) despite
what's in the database (10 - 19110 m range). So Deck is checking it out....
Will keep you posted so this issue can be addressed.

**Comment by maelle** [comment]
The API is no longer maintained therefore this package has been archived.
