### ISSUE TITLE
New dev API is ready

### ISSUE THREAD

**Issue by karthik** [ropensci/ecoengine#66]
New API is ready.

related issue: https://github.com/berkeley-gif/bee/issues/266#issuecomment-67558081

Due: Dec 31.

**Comment by postfalk** [comment]
Does it mean rOpenSci works properly? Just double-checking?

**Comment by karthik** [comment]
Not yet. Almost there but there are still a few issues to resolve.

**Comment by postfalk** [comment]
Ok. You might post an issue if you think the error is on my side OR if you
think the API would be the more appropriate place. I am happy to work on
this.

On Wed, Jan 7, 2015 at 12:43 PM, Karthik Ram <notifications@github.com>
wrote:

> Not yet. Almost there but there are still a few issues to resolve.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/66#issuecomment-69088641>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
@postfalk A couple of tests are failing and it seems like incorrect JSON being returned from your side:

```r
> ee_observations(genus__exact = "Pinus")
Error in parseJSON(txt) : lexical error: invalid char in json text.
                                       <html>  <head><title>502 Bad Ga
                     (right here) ------^
Calls: ee_observations ... <Anonymous> -> fromJSON_string -> parseJSON -> .Call
In addition: Warning message:
In ee_observations(genus__exact = "Pinus") :
  server error: (502) Bad Gateway
Calls: ee_observations -> warn_for_status
```

**Comment by postfalk** [comment]
It looks more like you get a 502 error which is probably a time out due to
the small instance the dev server is running on. I will explore.
Thx

On Wed, Jan 7, 2015 at 3:31 PM, Karthik Ram <notifications@github.com>
wrote:

> @postfalk <https://github.com/postfalk> A couple of tests are failing and
> it seems like incorrect JSON being returned from your side:
>
> > ee_observations(genus__exact = "Pinus")Error in parseJSON(txt) : lexical error: invalid char in json text.
>                                        <html>  <head><title>502 Bad Ga
>                      (right here) ------^Calls: ee_observations ... <Anonymous> -> fromJSON_string -> parseJSON -> .CallIn addition: Warning message:In ee_observations(genus__exact = "Pinus") :
>   server error: (502) Bad GatewayCalls: ee_observations -> warn_for_status
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/66#issuecomment-69111917>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
https://dev-ecoengine.berkeley.edu/api/observations/?genus_exact=pinus

worked for me can you rerun?

Falk

On Wed, Jan 7, 2015 at 3:36 PM, Falk Schuetzenmeister <
schuetzenmeister@berkeley.edu> wrote:

> It looks more like you get a 502 error which is probably a time out due to
> the small instance the dev server is running on. I will explore.
> Thx
>
> On Wed, Jan 7, 2015 at 3:31 PM, Karthik Ram <notifications@github.com>
> wrote:
>
>> @postfalk <https://github.com/postfalk> A couple of tests are failing
>> and it seems like incorrect JSON being returned from your side:
>>
>> > ee_observations(genus__exact = "Pinus")Error in parseJSON(txt) : lexical error: invalid char in json text.
>>                                        <html>  <head><title>502 Bad Ga
>>                      (right here) ------^Calls: ee_observations ... <Anonymous> -> fromJSON_string -> parseJSON -> .CallIn addition: Warning message:In ee_observations(genus__exact = "Pinus") :
>>   server error: (502) Bad GatewayCalls: ee_observations -> warn_for_status
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ropensci/ecoengine/issues/66#issuecomment-69111917>.
>>
>
>
>
> --
> Falk Schuetzenmeister, PhD
> Web Application Developer
> Geospatial Innovation Facility <http://gif.berkeley.edu/>
>
> University of California Berkeley
> 111 Mulford Hall
> 94720 Berkeley, CA
>
> schuetzenmeister@berkeley.edu
> 1-510-642-4897
>
>


-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
That worked, but removing that test led other tests to fail. You might be right that the small instance isn't able to return results fast enough.

**Comment by postfalk** [comment]
Correction:

https://dev-ecoengine.berkeley.edu/api/observations/?genus__exact=Pinus

On Wed, Jan 7, 2015 at 3:39 PM, Falk Schuetzenmeister <
schuetzenmeister@berkeley.edu> wrote:

> https://dev-ecoengine.berkeley.edu/api/observations/?genus_exact=pinus
>
> worked for me can you rerun?
>
> Falk
>
> On Wed, Jan 7, 2015 at 3:36 PM, Falk Schuetzenmeister <
> schuetzenmeister@berkeley.edu> wrote:
>
>> It looks more like you get a 502 error which is probably a time out due
>> to the small instance the dev server is running on. I will explore.
>> Thx
>>
>> On Wed, Jan 7, 2015 at 3:31 PM, Karthik Ram <notifications@github.com>
>> wrote:
>>
>>> @postfalk <https://github.com/postfalk> A couple of tests are failing
>>> and it seems like incorrect JSON being returned from your side:
>>>
>>> > ee_observations(genus__exact = "Pinus")Error in parseJSON(txt) : lexical error: invalid char in json text.
>>>                                        <html>  <head><title>502 Bad Ga
>>>                      (right here) ------^Calls: ee_observations ... <Anonymous> -> fromJSON_string -> parseJSON -> .CallIn addition: Warning message:In ee_observations(genus__exact = "Pinus") :
>>>   server error: (502) Bad GatewayCalls: ee_observations -> warn_for_status
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ropensci/ecoengine/issues/66#issuecomment-69111917>.
>>>
>>
>>
>>
>> --
>> Falk Schuetzenmeister, PhD
>> Web Application Developer
>> Geospatial Innovation Facility <http://gif.berkeley.edu/>
>>
>> University of California Berkeley
>> 111 Mulford Hall
>> 94720 Berkeley, CA
>>
>> schuetzenmeister@berkeley.edu
>> 1-510-642-4897
>>
>>
>
>
> --
> Falk Schuetzenmeister, PhD
> Web Application Developer
> Geospatial Innovation Facility <http://gif.berkeley.edu/>
>
> University of California Berkeley
> 111 Mulford Hall
> 94720 Berkeley, CA
>
> schuetzenmeister@berkeley.edu
> 1-510-642-4897
>
>


-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
Hi @postfalk 
The error shows up every single time. So if this is an issue with the dev being a small instance, there will be no way to resolve in the current state. I think you should just switch the API over and I'll quickly fix anything that stalls and will push a fix to CRAN. I don't think the plumbing itself has changed so we should be fine. Let me know once you do that, and I'll rerun the tests and fix any bugs. I don't think we need to wait longer unless there is more to do on the dev side.

**Comment by postfalk** [comment]
Ok, moving on with some improvements and will do that in a couple of weeks.
Could you please copy paste the request that fails.
Thx

On Sun, Jan 18, 2015 at 2:57 PM, Karthik Ram <notifications@github.com>
wrote:

> Hi @postfalk <https://github.com/postfalk>
> The error shows up every single time. So if this is an issue with the dev
> being a small instance, there will be no way to resolve in the current
> state. I think you should just switch the API over and I'll quickly fix
> anything that stalls and will push a fix to CRAN. I don't think the
> plumbing itself has changed so we should be fine. Let me know once you do
> that, and I'll rerun the tests and fix any bugs. I don't think we need to
> wait longer unless there is more to do on the dev side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/66#issuecomment-70430745>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
Same as before. See a few comments above.
