### ISSUE TITLE
Bug with new API change

### ISSUE THREAD

**Issue by karthik** [ropensci/ecoengine#69]
Via Scott.

```r
pinus <- ee_observations(scientific_name = "linepithema humile", page_size = 1)
#> Search contains 0 observations (downloading 1 of 0 pages)
#>  Error in names(obs_data_all) <- gsub("properties.", "", names(obs_data_all)) : 
#>   attempt to set an attribute on NULL
```

looks like the first line that's a problem is `names(obs_data_all) <- gsub("properties.", "", names(obs_data_all))` cause it's trying to set names on a NULL object.

@postfalk Did `properties` get dropped as a field?

**Comment by postfalk** [comment]
Is this on the old or on the new instance. The older one did not change. I
will explore. Could you please post the underlying http request.

Thank you, Falk

On Tue, Feb 24, 2015 at 10:00 AM, Karthik Ram <notifications@github.com>
wrote:

> Via Scott.
>
> pinus <- ee_observations(scientific_name = "linepithema humile", page_size = 1)#> Search contains 0 observations (downloading 1 of 0 pages)#>  Error in names(obs_data_all) <- gsub("properties.", "", names(obs_data_all)) : #>   attempt to set an attribute on NULL
>
> looks like the first line that's a problem is names(obs_data_all) <-
> gsub("properties.", "", names(obs_data_all)) cause it's trying to set
> names on a NULL object.
>
> @postfalk <https://github.com/postfalk> Did properties get dropped as a
> field?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/69>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
It's to the new one. I fixed this since it just turns out there is no data for that species name and the server does not return a helpful error message. Just returns `502`. Now I have a different issue with the sensor data but I'll post that as a new issue.

**Comment by postfalk** [comment]
Yes, there are still some holes in the error messaging that need to be
addressed. So it will be still nice to have the request.
Falk

On Tue, Feb 24, 2015 at 10:54 AM, Karthik Ram <notifications@github.com>
wrote:

> It's to the new one. I fixed this since it just turns out there is no data
> for that species name and the server does not return a helpful error
> message. Just returns 502. Now I have a different issue with the sensor
> data but I'll post that as a new issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/69#issuecomment-75820686>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
Problem is that everything is timing out, randomly failing calls and tests. This URL for e.g.

```
https://ecoengine.berkeley.edu/api/observations/?scientific_name=linepithema%20humile
```

returns a `200` most times but programmatic calls return `502`.

**Comment by postfalk** [comment]
I get an empty return on this one. Is this what you expect?

On Tue, Feb 24, 2015 at 11:45 AM, Karthik Ram <notifications@github.com>
wrote:

> Problem is that everything is timing out, randomly failing calls and
> tests. This URL for e.g.
>
> https://ecoengine.berkeley.edu/api/observations/?scientific_name=linepithema%20humile
>
> returns a 200 most times but programmatic calls return 502.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/69#issuecomment-75830703>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
Yes that is the intended behavior. But since we make calls to a bunch of sources in our `spocc` package, empty returns from one or more sources cannot break the entire call.

**Comment by postfalk** [comment]
Are you running against dev or production? Couldn't you catch 500, 502 in
your code? I know our API should not break on those. However, your code
should not break on faulty APIs either.

Thanks for reporting.

On Tue, Feb 24, 2015 at 11:55 AM, Karthik Ram <notifications@github.com>
wrote:

> Yes that is the intended behavior. But since we make calls to a bunch of
> sources in our spocc package, empty returns from one or more sources
> cannot break the entire call.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/69#issuecomment-75832737>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by sckott** [comment]
@karthik hmm, i still get that error

```r
ee_observations(scientific_name = "linepithema humile", page_size = 1)
#> Search contains 0 observations (downloading 1 of 0 pages)
#>   
#> Error in names(obs_data_all) <- gsub("properties.", "", names(obs_data_all)) : 
#>   attempt to set an attribute on NULL
```

```r
packageVersion("ecoengine")
#> [1] ‘1.8.99’
```

**Comment by karthik** [comment]
I see the problem. It doesn't catch requests that return no results. Fixing that now.

**Comment by karthik** [comment]
@sckott 
Is this behavior ok?

```r
> library(ecoengine)
> ee_observations(scientific_name = "linepithema humile", page_size = 1)
Error: obs_data$count not greater than 0
```

If there is a `tryCatch` it should catch such errors.

**Comment by sckott** [comment]
@karthik yeah, that works
