### ISSUE TITLE
Are you using geojson field in flat json return? Or are using format=geojson

### ISSUE THREAD

**Issue by postfalk** [ropensci/ecoengine#78]
I would like to move it to geometry in order to make it more concise. I could serve both fields for awhile. But would like to deprecate the geojson field just before more people would use Ecoengine.

Thoughts? How much trouble would this cause for you? Most other users are using the geojson returns which will be not affected.

Well I could also read the code to find out :)

Falk

**Comment by karthik** [comment]
I'm currently using `format=`geojson`. e.g. https://github.com/ropensci/ecoengine/blob/master/R/ee_observations.R#L77

Would I still have a problem if you move in even as I specifically request `=geojson`?

**Comment by postfalk** [comment]
Nope, if you use format=geojson the return should be unchanged.

However, I will let you test before I release anything with major changes.

Falk

On Sun, Apr 12, 2015 at 2:31 PM, Karthik Ram <notifications@github.com>
wrote:

> I'm currently using format=geojson`. e.g.
> https://github.com/ropensci/ecoengine/blob/master/R/ee_observations.R#L77
>
> Would I still have a problem if you move in even as I specifically request
> =geojson?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/78#issuecomment-92135844>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by karthik** [comment]
Excellent. Thank you. I won't be able to push another stable update till after May 1 anyway.
