### ISSUE TITLE
query and retrieve interaction fields 

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/ecoengine#79]
During the Moorea BIDS workshop, @mkoo suggested to integrate arctos records that contain species interactions into http://globalbioticinteractions.org . She documented this idea here: https://github.com/jhpoelen/eol-globi-data/issues/134 . I was able to retrieve the two records mentioned using the ecoengine, but could not find the interaction fields (see attached image) in the result. 

Two questions:
 1. How can I programmatically discover all records that contains species interactions? 
 1. How can I access the interaction fields stored in these records?

Thanks!

![screen shot 2015-04-29 at 9 49 00 am](https://cloud.githubusercontent.com/assets/1084872/7396393/244ddd32-ee90-11e4-9a22-36f4e70914be.png)

**Comment by karthik** [comment]
Hey @jhpoelen 
Can you tell me what query you ran? If it's returned by the ecoengine API I can certainly make sure it's in the result set.

**Comment by jhpoelen** [comment]
hi @kathik - I actually used https://ecoengine.berkeley.edu/api/observations/MVZ:Herp:241200/?fields= assuming that ecoengine R lib talk to that. The result do not seem to include the relationship terms. Perhaps you can help me figure out how to extract that data. 

Thanks!

**Comment by karthik** [comment]
Thanks for the additional info @jhpoelen 
I'll look into it and get back to you shortly.

**Comment by postfalk** [comment]
Well that is currently not in the Ecoengine. But it would be great to integrate this. Honestly, I still don't understand why we develop this stiff separately from each other.

**Comment by jhpoelen** [comment]
@postfalk @karthik while ecoengine is working on adding the access to interaction data records to the api, I was wondering whether I can easily grab the data directly from arctos. What method do you used to mine the collection data from Arctos?

**Comment by postfalk** [comment]
I get IPT dumps, I am not sure whether the contain interactions. You should ask @mkoo.

**Comment by karthik** [comment]
Hi @jhpoelen Just an FYI, I currently have various deadlines and travel through mid-May, so I wont be adding this for at least another two weeks. I'll ping this thread once I do.

**Comment by jhpoelen** [comment]
@posfalk are these IPT dump public? can I have a peek perhaps?

**Comment by postfalk** [comment]
Most IPT archives are public. However, I think you should ask @mkoo which
one contains the information you are looking for. I really do not know
about this part of arctos.
Falk

On Fri, May 1, 2015 at 10:58 AM, Jorrit Poelen <notifications@github.com>
wrote:

> @posfalk are these IPT dump public? can I have a peek perhaps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/ecoengine/issues/79#issuecomment-98188231>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by jhpoelen** [comment]
@postfalk @karthik I found that vertnet provides an api that is able to retrieve the ```associatedOccurrences``` fields. It would be nice to have it in ecoengine apis. However, I am able to access data now, so am closing issue. Please do let me know if you support the field in the future - I'd be happy to have a look at integrating with ecoengine again. 

Thanks for your quick replies.

**Comment by mkoo** [comment]
Sorry for missing this thread. Quick comment: after next week, I'll be able
to speak directly to this. IPTs generally are not set up for interactions
since it's not well enforced nor well structured for this. However Arctos
as a multicollection content management system is. I think there may be a
report that we can generate that is suited for GloBI with those
specimen/species interactions. I already mentioned this to my Arctos
colleagues and they are interested!
I'll return to this in a week (post-deadlines and end of semester) with
more info! thx
