### ISSUE TITLE
ee_map is broken

### ISSUE THREAD

**Issue by karthik** [ropensci/ecoengine#81]
This really needs to be reworked. The scales are problematic as well.
Perhaps this would be the time to switch to leaflet

**Comment by mkoo** [comment]
This would be great. I was going to try to swing an RShiny app with ee_map
as the output so I vote for an updated and working ee_map (or equivalent).

**Comment by karthik** [comment]
@mkoo This has more to do with the ecoengine API changing so regularly that the map keeps breaking. Same code, in contrast, in the `AntWeb` package has been super stable :frowning:

But nevertheless I am working towards replacing leaflet with mapbox.

See experiments here: http://karthik.github.io/mapbox-test/
