### ISSUE TITLE
Taxonomy endpoint?

### ISSUE THREAD

**Issue by sckott** [ropensci/ecoengine#84]
Is there an endpoint for getting unique names?  I'd like to query just the names ecoengine has, `/search` kinda does that, but doesn't give the full hierarchy of info, `/observations` is more flexible search wise, but have to pull back lots of observations to just get unique names. Maybe i'm missing a solution that's already here?

**Comment by karthik** [comment]
Not sure if it's exposed but I'll find out and update this thread.

**Comment by sckott** [comment]
Okay, this is to be able to let spocc users search for names used in ecoengine (along with other data sources), but just realized that maybe we should encourage users to use taxize to search for names since that's what it specializes in, so why reinvent that in spocc - but would still be useful to have a names endpoint in their API

**Comment by karthik** [comment]
Got it. I'm sure it's quite simple to expose in a end point (basically a unique on these fields). I'll update once I hear back.
