### ISSUE TITLE
Change leafletR import

### ISSUE THREAD

**Issue by sckott** [ropensci/ecoengine#85]
b/c `leafletR` is imported in this pkg, and in `AntWeb`, and both pkgs are imported in `spocc`, I can't use `leaflet` b/c `leafletR` has the function `leafletR:::print.leaflet`. Even though it's not exported (See triple colon), it still causes leaflet to completely fail since on creation of an object it assigns it as an S3 `leaflet` class - then the `leafletR:::print.leaflet` is called, and it fails

I'd like to use `leaflet` in `spoccutils` - so I wonder if you'd be willing to put `leafletR` in Suggests in this package and in `AntWeb` - I tested this locally, and it solves this issue - users could still use plotting fxns in ecoengine and antweb, but then `leafletR:::print.leaflet` doesn't get imported into the global namespace unless users use those functions.

**Comment by karthik** [comment]
ok got it. I can change both and push an update by next week.

**Comment by sckott** [comment]
Cool, thanks.
