### ISSUE TITLE
Ecoengine API - something changed?

### ISSUE THREAD

**Issue by sckott** [ropensci/ecoengine#90]
Tests that involve ecoengine with `spocc` are failing, and failures in the ecoengine tests

```r
➜  ecoengine git:(master) Rscript -e 'devtools::test()'
 :) R version 3.3.0 Patched (2016-05-09 r70593)Loading ecoengine
Loading required package: testthat
Testing ecoengine
Testing Ecoengine metadata functions: .............12
  |======================================================================| 100%
  |===================================                                   |  50%3
Testing observations: 4
eebind works correctly: 5
Testing checklists: .6
  |======================================================================| 100%
```

any idea if something's changed on their end?

**Comment by karthik** [comment]
I'm not sure, but I also got an email from BDR. I'm working on getting all these issues resolved over the weekend.

**Comment by karthik** [comment]
I've been speaking with the developers. It's super weird. The API works but it looks like the database access has been lost or erased. Speaking with @mkoo about finding a solution. Will keep this thread updated.

**Comment by karthik** [comment]
The API is back up and I've fixed a whole bunch of issues and resubmitted to CRAN. I've removed the mapping feature since that needs a good bit of reworking. I tried to use mapr out of the box but that didn't work but I'll push that feature back in the next update.
