### ISSUE TITLE
How to make ee_observations() not fail when no records found

### ISSUE THREAD

**Issue by kpmainali** [ropensci/ecoengine#96]
That is because I use it in the loop and need it keep going when no records are found. tryCatch() and if() next do not help my situation.

ee_observations(scientific_name = "Drymarchon couperi", progress = FALSE, page = "all", georeferenced = TRUE)

**Comment by karthik** [comment]
I'll push a fix in the next update but here is a way to fix this temporarily.

```r
library(ecoengine)
library(purrr)

ee_observations(
  scientific_name = "Drymarchon couperi",
  progress = FALSE,
  page = "all",
  georeferenced = TRUE
)
# Error: obs_data$count not greater than 0
# Let's fix this by wrapping with purrr's safely
safe_ee <- safely(ee_observations, otherwise = NULL)

safe_ee(
  scientific_name = "Drymarchon couperi",
  progress = FALSE,
  page = "all",
  georeferenced = TRUE
)

# This now returns NULL which you can capture and process.

```

**Comment by maelle** [comment]
The API is no longer maintained therefore this package has been archived.
